name: Build ReverseSSH

permissions:
  contents: write  # 允许推送代码到仓库

on:
  workflow_dispatch:
  push:
      branches: [ main ]
      paths:
        - '.github/workflows/Build-ReverseSSH.yaml'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone reverse-ssh repo
        run: |
          git clone https://github.com/Fahrj/reverse-ssh.git
          cd reverse-ssh

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Install upx
        run: sudo apt-get update && sudo apt-get install -y upx-ucl

      - name: Build with Makefile
        working-directory: reverse-ssh
        env:
          RS_PASS: ${{ secrets.RS_PASS }}
        run: |
          make compressed


      - name: Commit binaries
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          mkdir -p binaries/
          cp bin/*reverse-ssh* binaries/

          git add binaries/
          git commit -m "Add reverse-ssh binaries (make compressed)" || echo "No changes to commit"
          git push || echo "Push skipped or failed"
