name: Build tmux (static)

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-tmux.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取自身仓库
        uses: actions/checkout@v4

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake pkg-config libevent-dev libncurses-dev

      - name: 拉取 tmux 源码
        run: |
          git clone https://github.com/tmux/tmux.git
          cd tmux
          sh autogen.sh
          ./configure CFLAGS="-static" LDFLAGS="-static"
          make -j$(nproc)
          mkdir -p $GITHUB_WORKSPACE/bin
          cp tmux $GITHUB_WORKSPACE/bin/

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: tmux-static
          path: ${{ github.workspace }}/bin/tmux

      - name: 提交产物到主线
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/
          git commit -m "Add static tmux binary built from $GITHUB_SHA" || echo "无变化可提交"
          git push || echo "推送失败或无需推送"
