name: Build PRoot v5.4.0

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        run: |
          git clone --branch v5.4.0 https://github.com/proot-me/proot.git
          cd proot
          echo "SRC_DIR=$PWD" >> $GITHUB_ENV
          mkdir -p $GITHUB_WORKSPACE/bin

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libarchive-dev libtalloc-dev

      - name: Build for x86_64 (static)
        run: |
          cd $SRC_DIR/src
          make clean
          make -j$(nproc) LDFLAGS="-static"
          cp proot $GITHUB_WORKSPACE/bin/proot-x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proot-x86_64
          path: bin/proot-x86_64
