name: Build PRoot v5.4.0 (static)

on:
  push:
      branches: [ main ]
      paths:
        - '.github/workflows/build-proot.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          # 安装基础编译工具
          sudo apt-get install -y build-essential git libarchive-dev libtalloc-dev
          
          # 根据架构安装相应的工具链
          if [ "${{ matrix.arch }}" = "aarch64" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            # 尝试安装 aarch64 架构的开发库，如果失败则继续
            sudo apt-get install -y libarchive-dev:aarch64 libtalloc-dev:aarch64 || true
          fi

      - name: Fetch proot v5.4.0 source
        run: |
          git clone --depth=1 --branch v5.4.0 https://github.com/proot-me/proot.git
          echo "SRC_DIR=$PWD/proot" >> $GITHUB_ENV
          mkdir -p bin

      - name: Build for ${{ matrix.arch }}
        run: |
          cd $SRC_DIR/src
          make clean
          
          # 直接移除 Python 扩展目录，确保不会编译
          rm -rf extension/python/
          
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
            make -j$(nproc) LDFLAGS="-static"
            cp proot $GITHUB_WORKSPACE/bin/proot-${{ matrix.arch }}
          else
            make -j$(nproc) CC="aarch64-linux-gnu-gcc" LDFLAGS="-static"
            cp proot $GITHUB_WORKSPACE/bin/proot-${{ matrix.arch }}
          fi

      - name: Verify binary
        run: |
          echo "验证 ${{ matrix.arch }} 架构的二进制文件:"
          file $GITHUB_WORKSPACE/bin/proot-${{ matrix.arch }}
          echo "检查是否为静态链接:"
          # 对于静态二进制文件，ldd 会报错，这是正常的
          ldd $GITHUB_WORKSPACE/bin/proot-${{ matrix.arch }} 2>&1 | grep -q "not a dynamic executable" && echo "✓ 静态二进制文件: 成功" || echo "⚠ 不是静态二进制文件!"

      - name: Commit binaries
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/
          git commit -m "Add static proot binaries for ${{ matrix.arch }} (built without extensions)" || echo "没有变化可提交"
          git push || echo "推送失败或无需推送"
