name: Build PRoot v5.4.0 (static x86_64)

on:
  workflow_dispatch:   # 仅手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git \
            libarchive-dev libtalloc-dev

      - name: Fetch proot v5.4.0 source
        run: |
          git clone --branch v5.4.0 https://github.com/proot-me/proot.git
          echo "SRC_DIR=$PWD/proot" >> $GITHUB_ENV
          mkdir -p bin

      - name: Build static proot (x86_64)
        run: |
          cd $SRC_DIR/src
          make clean
          make -j$(nproc) LDFLAGS="-static" EXTENSIONS=""
          cp proot $GITHUB_WORKSPACE/bin/proot-x86_64

      - name: Commit binary into bin/
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/
          git commit -m "Add static proot binary (x86_64)"
          git push
