name: Build PRoot v5.4.0 (static)
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
      branches: [ main ]
      paths:
        - '.github/workflows/build-proot.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取自身git仓库
        uses: actions/checkout@v4
      - name: 启动 docker
        run: docker run -i -d --name=gcc gcc:7.4.0 bash

      - name: 安装依赖
        run: |
          docker exec gcc bash -c "sed -i 's|deb.debian.org/debian|archive.debian.org/debian|g' /etc/apt/sources.list"
          docker exec gcc bash -c "sed -i 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list"
          docker exec gcc bash -c "echo 'Acquire::Check-Valid-Until \"false\";' > /etc/apt/apt.conf.d/99ignore-valid-until"
          docker exec gcc bash -c "apt-get update -qq"
          docker exec gcc bash -c "apt-get install -y git clang-tools-6.0 curl docutils-common gdb lcov libarchive-dev libtalloc-dev strace swig uthash-dev xsltproc"

      - name: 拉取存储库
        run: docker exec gcc bash -c "git clone https://gitlab.com/proot/proot.git /proot"

      - name: 构建
        run: |
          docker exec gcc bash -c 'LDFLAGS="${LDFLAGS} -static" make -C /proot/src proot'
          mkdir -p $GITHUB_WORKSPACE/bin
          docker cp gcc:/proot/src/proot $GITHUB_WORKSPACE/bin
      - name: 下载产物
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ${{ github.workspace }}/bin/proot-x86_64

      - name: Commit binaries
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/
          git commit -m "Add static PRoot binary built from $GITHUB_SHA" || echo "无变化可提交"
          git push || echo "推送失败或无需推送"

